// <auto-generated />
using System;
using EFCore3MigrationBug;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore3MigrationBug.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore3MigrationBug.Blog", b =>
                {
                    b.Property<Guid>("BlogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("BlogId");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("EFCore3MigrationBug.Blog", b =>
                {
                    b.OwnsMany("EFCore3MigrationBug.Blog+Post", "Posts", b1 =>
                        {
                            b1.Property<Guid>("BlogId");

                            b1.Property<Guid>("PostId");

                            b1.Property<string>("Name");

                            b1.HasKey("BlogId", "PostId");

                            b1.ToTable("Post");

                            b1.HasOne("EFCore3MigrationBug.Blog")
                                .WithMany("Posts")
                                .HasForeignKey("BlogId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsMany("EFCore3MigrationBug.Blog+Post+Attachment", "Attachments", b2 =>
                                {
                                    b2.Property<Guid>("BlogId");

                                    b2.Property<Guid>("PostId");

                                    b2.Property<Guid>("AttachmentId");

                                    b2.Property<string>("Name");

                                    b2.HasKey("BlogId", "PostId", "AttachmentId")
                                        .HasAnnotation("SqlServer:Clustered", true);

                                    b2.ToTable("Attachment");

                                    b2.HasOne("EFCore3MigrationBug.Blog+Post")
                                        .WithMany("Attachments")
                                        .HasForeignKey("BlogId", "PostId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
